FROM ruby:2.4.1

# Install qt & xvfb (virtual X) for capybara-webkit
RUN apt-get update -y; true && apt-get install -y xvfb iceweasel netcat
RUN wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz \
         -O /tmp/geckodriver-v0.18.0-linux64.tar.gz && \
         tar -xvzf /tmp/geckodriver-v0.18.0-linux64.tar.gz && \
         mv geckodriver /usr/local/bin/ && \
         rm -f /tmp/geckodriver-v0.18.0-linux64.tar.gz
