references:
  defaults: &defaults
    working_directory: ~/repo

  github_team_name_slug: &github_team_name_slug
    GITHUB_TEAM_NAME_SLUG: prison-visits-booking

  test_container_config: &test_container_config
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
        environment:
          START_PAGE: "https://prison-visits-public-staging.apps.live-1.cloud-platform.service.justice.gov.uk/en/request"

version: 2
jobs:
  install_dependencies:
    <<: *defaults
    <<: *test_container_config
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Which bundler?
          command: bundle -v
      - restore_cache:
          keys:
            -  prison-visits-integration-tests-{{ checksum "Gemfile.lock" }}
      - run: bundle check --path vendor/bundle || bundle install --path vendor/bundle
      - save_cache:
          key:  prison-visits-integration-tests-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/repo/vendor/bundle
      - persist_to_workspace:
          root: .
          paths:
            - vendor/bundle

  smoke_test:
    <<: *defaults
    <<: *test_container_config
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: bundle --path vendor/bundle
      - run:
          name: Run tests
          command: |
            bundle exec rspec spec/smoke

workflows:
  version: 2
  build_and_smoke_test:
    jobs:
      - install_dependencies
      - smoke_test:
          requires:
            - install_dependencies